#!/bin/bash -eu
VERSION=`cat VERSION`

USER=`cat USER`
BUILDING=`cat BUILDING`
PRODUCTION=`cat PRODUCTION`
INNER1=`cat INNER1`

deploy() {
    build
    download $VERSION
    upload
    upgrade $VERSION
}

version() {
    echo $VERSION
}

fixversion() {
    hg commit -m "fix version $VERSION" mix.exs VERSION
    hg push
}

build() {
    fixversion

    ssh ${USER}@${BUILDING} "rm -rf src/exantenna/priv/static/css/*"
    ssh ${USER}@${BUILDING} "rm -rf src/exantenna/priv/static/js/*"
    ssh ${USER}@${BUILDING} "cd src/exantenna && bash build"
}

download() {
    rsync -avr --stats ${USER}@${BUILDING}:~/src/exantenna/rel .

    (cd rel/exantenna
        rm -rf  static
        ln -fs lib/exantenna-${VERSION}/priv/static
    )
}

upload() {
    # upload staging
    rsync -avr --stats rel ${USER}@${PRODUCTION}:~/

    # TODO: rsync to be background process if additional more INNER server.
    bash mix run for_inners.exs
    rsync -avr --stats rel ${USER}@${INNER1}:~/
}

upgrade() {
    # upgrade
    ssh ${USER}@${PRODUCTION} "(cd src/exantenna; hg pull ; hg up -C)"
    ssh ${USER}@${PRODUCTION} "sh rel/exantenna/bin/exantenna upgrade $1"

    ssh ${USER}@${INNER1} "(cd src/exantenna; hg pull ; hg up -C)"
    ssh ${USER}@${INNER1} "sh rel/exantenna/bin/exantenna upgrade $1"

    restartsrv

    echo;deployed
}

restartsrv() {
    set +e

    OUT=`ssh ${USER}@${INNER1} "ps aux | grep '/rel/exantenna/bin/exantenna' | grep -v 'grep'"`
    echo "INNER1 OUT: $OUT"
    ssh ${USER}@${INNER1} "sudo systemctl restart phoenix"
    ssh ${USER}@${INNER1} "sudo systemctl start phoenix"
    ssh ${USER}@${INNER1} "sudo systemctl start phoenix"
    ssh ${USER}@${INNER1} "sudo systemctl start phoenix"
    OUT=`ssh ${USER}@${INNER1} "ps aux | grep '/rel/exantenna/bin/exantenna' | grep -v 'grep'"`
    echo "INNER1 OUT: $OUT"

    OUT=`ssh ${USER}@${PRODUCTION} "ps aux | grep '/rel/exantenna/bin/exantenna' | grep -v 'grep'"`
    echo;echo "PRODUCTION OUT: $OUT"
    ssh ${USER}@${PRODUCTION} "sudo systemctl restart phoenix"
    ssh ${USER}@${PRODUCTION} "sudo systemctl start phoenix"
    ssh ${USER}@${PRODUCTION} "sudo systemctl start phoenix"
    ssh ${USER}@${PRODUCTION} "sudo systemctl start phoenix"
    OUT=`ssh ${USER}@${PRODUCTION} "ps aux | grep '/rel/exantenna/bin/exantenna' | grep -v 'grep'"`
    echo "PRODUCTION OUT: $OUT"

    set -e
}

downgrade() {
    # upgrade
    ssh ${USER}@${PRODUCTION} "sh rel/exantenna/bin/exantenna downgrade $1"
    ssh ${USER}@${INNER1}     "sh rel/exantenna/bin/exantenna downgrade $1"

    echo;deployed
}

remove() {
    rm -fr rel/exantenna/lib/exantenna-$1
    rm -fr rel/exantenna/releases/$1

    rsync -avr --delete --stats rel/exantenna/lib      ${USER}@${BUILDING}:~/src/exantenna/rel/exantenna/
    rsync -avr --delete --stats rel/exantenna/releases ${USER}@${BUILDING}:~/src/exantenna/rel/exantenna/

    rsync -avr --delete --stats rel/exantenna/lib      ${USER}@${PRODUCTION}:~/rel/exantenna/
    rsync -avr --delete --stats rel/exantenna/releases ${USER}@${PRODUCTION}:~/rel/exantenna/

    rsync -avr --delete --stats rel/exantenna/lib      ${USER}@${INNER1}:~/rel/exantenna/
    rsync -avr --delete --stats rel/exantenna/releases ${USER}@${INNER1}:~/rel/exantenna/
}

deployed() {
    # upgrade
    echo "PRODUCTION"
    ssh ${USER}@${PRODUCTION} "ls -t rel/exantenna/releases"

    echo "INNER1"
    ssh ${USER}@${INNER1} "ls -t rel/exantenna/releases"
}

case "$1" in
    deploy)             deploy            ;;
    version)            version           ;;
    fixversion)         fixversion        ;;
    build)              build             ;;
    upload)             upload            ;;
    download)           download          ;;
    upgrade)            upgrade $2        ;;
    downgrade)          downgrade $2      ;;
    deployed)           deployed          ;;
    remove)             remove $2         ;;
    restart)            restartsrv        ;;
    *) echo "
Usage:
    $0 <command> [options]

Commands:
    deploy                    Deployment all
    version                   Get package version.
    fixversion <version>      Fix package version.
    build      [options]      Build packages.
    upload                    UploadDeplo packages.
    download   <version>      Download rel.
    upgrade    <version>      Upload rel.
    downgrade  <version>      Hot deploy server.
    deployed                  Deployed versions.
    remove                    Removing before versions.
    restart                   Restarting servers

" >&2
       exit 1
       ;;
esac
