defmodule Exantenna.Word.Character do
  @moduledoc false

  def human_atoz(locale, str) do
    case locale do
      "en" ->
        case str do
          "a"  -> "A"
          "i"  -> "I"
          "u"  -> "U"
          "e"  -> "E"
          "o"  -> "O"
          "ka" -> "Ka"
          "ki" -> "Ki"
          "ku" -> "Ku"
          "ke" -> "Ke"
          "ko" -> "Ko"
          "sa" -> "Sa"
          "si" -> "Shi"
          "su" -> "Su"
          "se" -> "Se"
          "so" -> "So"
          "ta" -> "Ta"
          "ti" -> "Chi"
          "tu" -> "Tsu"
          "te" -> "Te"
          "to" -> "To"
          "na" -> "Na"
          "ni" -> "Ni"
          "nu" -> "Nu"
          "ne" -> "Ne"
          "no" -> "No"
          "ha" -> "Ha"
          "hi" -> "Hi"
          "hu" -> "Fu"
          "he" -> "He"
          "ho" -> "Ho"
          "ma" -> "Ma"
          "mi" -> "Mi"
          "mu" -> "Mu"
          "me" -> "Me"
          "mo" -> "Mo"
          "ya" -> "Ya"
          "yu" -> "Yu"
          "yo" -> "Yo"
          "ra" -> "Ra"
          "ri" -> "Ri"
          "ru" -> "Ru"
          "re" -> "Re"
          "ro" -> "Ro"
          "wa" -> "Wo"
        end
      "ja" ->
        case str do
          "a"  -> "あ"
          "i"  -> "い"
          "u"  -> "う"
          "e"  -> "え"
          "o"  -> "お"
          "ka" -> "か"
          "ki" -> "き"
          "ku" -> "く"
          "ke" -> "け"
          "ko" -> "こ"
          "sa" -> "さ"
          "si" -> "し"
          "su" -> "す"
          "se" -> "せ"
          "so" -> "そ"
          "ta" -> "た"
          "ti" -> "ち"
          "tu" -> "つ"
          "te" -> "て"
          "to" -> "と"
          "na" -> "な"
          "ni" -> "に"
          "nu" -> "ぬ"
          "ne" -> "ね"
          "no" -> "の"
          "ha" -> "は"
          "hi" -> "ひ"
          "hu" -> "ふ"
          "he" -> "へ"
          "ho" -> "ほ"
          "ma" -> "ま"
          "mi" -> "み"
          "mu" -> "む"
          "me" -> "め"
          "mo" -> "も"
          "ya" -> "や"
          "yu" -> "ゆ"
          "yo" -> "よ"
          "ra" -> "ら"
          "ri" -> "り"
          "ru" -> "る"
          "re" -> "れ"
          "ro" -> "ろ"
          "wa" -> "を"
        end
    end
  end

end
