glyphicon:
- glyphicon-asterisk
- glyphicon-plus
- glyphicon-euro
- glyphicon-eur
- glyphicon-minus
- glyphicon-cloud
- glyphicon-envelope
- glyphicon-pencil
- glyphicon-glass
- glyphicon-music
- glyphicon-search
- glyphicon-heart
- glyphicon-star
- glyphicon-star-empty
- glyphicon-user
- glyphicon-film
- glyphicon-th-large
- glyphicon-th
- glyphicon-th-list
- glyphicon-ok
- glyphicon-remove
- glyphicon-zoom-in
- glyphicon-zoom-out
- glyphicon-off
- glyphicon-signal
- glyphicon-cog
- glyphicon-trash
- glyphicon-home
- glyphicon-file
- glyphicon-time
- glyphicon-road
- glyphicon-download-alt
- glyphicon-download
- glyphicon-upload
- glyphicon-inbox
- glyphicon-play-circle
- glyphicon-repeat
- glyphicon-refresh
- glyphicon-list-alt
- glyphicon-lock
- glyphicon-flag
- glyphicon-headphones
- glyphicon-volume-off
- glyphicon-volume-down
- glyphicon-volume-up
- glyphicon-qrcode
- glyphicon-barcode
- glyphicon-tag
- glyphicon-tags
- glyphicon-book
- glyphicon-bookmark
- glyphicon-print
- glyphicon-camera
- glyphicon-font
- glyphicon-bold
- glyphicon-italic
- glyphicon-text-height
- glyphicon-text-width
- glyphicon-align-left
- glyphicon-align-center
- glyphicon-align-right
- glyphicon-align-justify
- glyphicon-list
- glyphicon-indent-left
- glyphicon-indent-right
- glyphicon-facetime-video
- glyphicon-picture
- glyphicon-map-marker
- glyphicon-adjust
- glyphicon-tint
- glyphicon-edit
- glyphicon-share
- glyphicon-check
- glyphicon-move
- glyphicon-step-backward
- glyphicon-fast-backward
- glyphicon-backward
- glyphicon-play
- glyphicon-pause
- glyphicon-stop
- glyphicon-forward
- glyphicon-fast-forward
- glyphicon-step-forward
- glyphicon-eject
- glyphicon-chevron-left
- glyphicon-chevron-right
- glyphicon-plus-sign
- glyphicon-minus-sign
- glyphicon-remove-sign
- glyphicon-ok-sign
- glyphicon-question-sign
- glyphicon-info-sign
- glyphicon-screenshot
- glyphicon-remove-circle
- glyphicon-ok-circle
- glyphicon-ban-circle
- glyphicon-arrow-left
- glyphicon-arrow-right
- glyphicon-arrow-up
- glyphicon-arrow-down
- glyphicon-share-alt
- glyphicon-resize-full
- glyphicon-resize-small
- glyphicon-exclamation-sign
- glyphicon-gift
- glyphicon-leaf
- glyphicon-fire
- glyphicon-eye-open
- glyphicon-eye-close
- glyphicon-warning-sign
- glyphicon-plane
- glyphicon-calendar
- glyphicon-random
- glyphicon-comment
- glyphicon-magnet
- glyphicon-chevron-up
- glyphicon-chevron-down
- glyphicon-retweet
- glyphicon-shopping-cart
- glyphicon-folder-close
- glyphicon-folder-open
- glyphicon-resize-vertical
- glyphicon-resize-horizontal
- glyphicon-hdd
- glyphicon-bullhorn
- glyphicon-bell
- glyphicon-certificate
- glyphicon-thumbs-up
- glyphicon-thumbs-down
- glyphicon-hand-right
- glyphicon-hand-left
- glyphicon-hand-up
- glyphicon-hand-down
- glyphicon-circle-arrow-right
- glyphicon-circle-arrow-left
- glyphicon-circle-arrow-up
- glyphicon-circle-arrow-down
- glyphicon-globe
- glyphicon-wrench
- glyphicon-tasks
- glyphicon-filter
- glyphicon-briefcase
- glyphicon-fullscreen
- glyphicon-dashboard
- glyphicon-paperclip
- glyphicon-heart-empty
- glyphicon-link
- glyphicon-phone
- glyphicon-pushpin
- glyphicon-usd
- glyphicon-gbp
- glyphicon-sort
- glyphicon-sort-by-alphabet
- glyphicon-sort-by-alphabet-alt
- glyphicon-sort-by-order
- glyphicon-sort-by-order-alt
- glyphicon-sort-by-attributes
- glyphicon-sort-by-attributes-alt
- glyphicon-unchecked
- glyphicon-expand
- glyphicon-collapse-down
- glyphicon-collapse-up
- glyphicon-log-in
- glyphicon-flash
- glyphicon-log-out
- glyphicon-new-window
- glyphicon-record
- glyphicon-save
- glyphicon-open
- glyphicon-saved
- glyphicon-import
- glyphicon-export
- glyphicon-send
- glyphicon-floppy-disk
- glyphicon-floppy-saved
- glyphicon-floppy-remove
- glyphicon-floppy-save
- glyphicon-floppy-open
- glyphicon-credit-card
- glyphicon-transfer
- glyphicon-cutlery
- glyphicon-header
- glyphicon-compressed
- glyphicon-earphone
- glyphicon-phone-alt
- glyphicon-tower
- glyphicon-stats
- glyphicon-sd-video
- glyphicon-hd-video
- glyphicon-subtitles
- glyphicon-sound-stereo
- glyphicon-sound-dolby
- glyphicon-sound-5-1
- glyphicon-sound-6-1
- glyphicon-sound-7-1
- glyphicon-copyright-mark
- glyphicon-registration-mark
- glyphicon-cloud-download
- glyphicon-cloud-upload
- glyphicon-tree-conifer
- glyphicon-tree-deciduous

icomoon:
- icon-home
- icon-home2
- icon-home3
- icon-office
- icon-newspaper
- icon-pencil
- icon-pencil2
- icon-quill
- icon-pen
- icon-blog
- icon-droplet
- icon-paint-format
- icon-image
- icon-image2
- icon-images
- icon-camera
- icon-music
- icon-headphones
- icon-play
- icon-film
- icon-camera2
- icon-dice
- icon-pacman
- icon-spades
- icon-clubs
- icon-diamonds
- icon-pawn
- icon-bullhorn
- icon-connection
- icon-podcast
- icon-feed
- icon-book
- icon-books
- icon-library
- icon-file
- icon-profile
- icon-file2
- icon-file3
- icon-file4
- icon-copy
- icon-copy2
- icon-copy3
- icon-paste
- icon-paste2
- icon-paste3
- icon-stack
- icon-folder
- icon-folder-open
- icon-tag
- icon-tags
- icon-barcode
- icon-qrcode
- icon-ticket
- icon-cart
- icon-cart2
- icon-cart3
- icon-coin
- icon-credit
- icon-calculate
- icon-support
- icon-phone
- icon-phone-hang-up
- icon-address-book
- icon-notebook
- icon-envelope
- icon-pushpin
- icon-location
- icon-location2
- icon-compass
- icon-map
- icon-map2
- icon-history
- icon-clock
- icon-clock2
- icon-alarm
- icon-alarm2
- icon-bell
- icon-stopwatch
- icon-calendar
- icon-calendar2
- icon-print
- icon-keyboard
- icon-screen
- icon-laptop
- icon-mobile
- icon-mobile2
- icon-tablet
- icon-tv
- icon-cabinet
- icon-drawer
- icon-drawer2
- icon-drawer3
- icon-box-add
- icon-box-remove
- icon-download
- icon-upload
- icon-disk
- icon-storage
- icon-undo
- icon-redo
- icon-flip
- icon-flip2
- icon-undo2
- icon-redo2
- icon-forward
- icon-reply
- icon-bubble
- icon-bubbles
- icon-bubbles2
- icon-bubble2
- icon-bubbles3
- icon-bubbles4
- icon-user
- icon-users
- icon-user2
- icon-users2
- icon-user3
- icon-user4
- icon-quotes-left
- icon-busy
- icon-spinner
- icon-spinner2
- icon-spinner3
- icon-spinner4
- icon-spinner5
- icon-spinner6
- icon-binoculars
- icon-search
- icon-zoomin
- icon-zoomout
- icon-expand
- icon-contract
- icon-expand2
- icon-contract2
- icon-key
- icon-key2
- icon-lock
- icon-lock2
- icon-unlocked
- icon-wrench
- icon-settings
- icon-equalizer
- icon-cog
- icon-cogs
- icon-cog2
- icon-hammer
- icon-wand
- icon-aid
- icon-bug
- icon-pie
- icon-stats
- icon-bars
- icon-bars2
- icon-gift
- icon-trophy
- icon-glass
- icon-mug
- icon-food
- icon-leaf
- icon-rocket
- icon-meter
- icon-meter2
- icon-dashboard
- icon-hammer2
- icon-fire
- icon-lab
- icon-magnet
- icon-remove
- icon-remove2
- icon-briefcase
- icon-airplane
- icon-truck
- icon-road
- icon-accessibility
- icon-target
- icon-shield
- icon-lightning
- icon-switch
- icon-powercord
- icon-signup
- icon-list
- icon-list2
- icon-numbered-list
- icon-menu
- icon-menu2
- icon-tree
- icon-cloud
- icon-cloud-download
- icon-cloud-upload
- icon-download2
- icon-upload2
- icon-download3
- icon-upload3
- icon-globe
- icon-earth
- icon-link
- icon-flag
- icon-attachment
- icon-eye
- icon-eye-blocked
- icon-eye2
- icon-bookmark
- icon-bookmarks
- icon-brightness-medium
- icon-brightness-contrast
- icon-contrast
- icon-star
- icon-star2
- icon-star3
- icon-heart
- icon-heart2
- icon-heart-broken
- icon-thumbs-up
- icon-thumbs-up2
- icon-happy
- icon-happy2
- icon-smiley
- icon-smiley2
- icon-tongue
- icon-tongue2
- icon-sad
- icon-sad2
- icon-wink
- icon-wink2
- icon-grin
- icon-grin2
- icon-cool
- icon-cool2
- icon-angry
- icon-angry2
- icon-evil
- icon-evil2
- icon-shocked
- icon-shocked2
- icon-confused
- icon-confused2
- icon-neutral
- icon-neutral2
- icon-wondering
- icon-wondering2
- icon-point-up
- icon-point-right
- icon-point-down
- icon-point-left
- icon-warning
- icon-notification
- icon-question
- icon-info
- icon-info2
- icon-blocked
- icon-cancel-circle
- icon-checkmark-circle
- icon-spam
- icon-close
- icon-checkmark
- icon-checkmark2
- icon-spell-check
- icon-minus
- icon-plus
- icon-enter
- icon-exit
- icon-play2
- icon-pause
- icon-stop
- icon-backward
- icon-forward2
- icon-play3
- icon-pause2
- icon-stop2
- icon-backward2
- icon-forward3
- icon-first
- icon-last
- icon-previous
- icon-next
- icon-eject
- icon-volume-high
- icon-volume-medium
- icon-volume-low
- icon-volume-mute
- icon-volume-mute2
- icon-volume-increase
- icon-volume-decrease
- icon-loop
- icon-loop2
- icon-loop3
- icon-shuffle
- icon-arrow-up-left
- icon-arrow-up
- icon-arrow-up-right
- icon-arrow-right
- icon-arrow-down-right
- icon-arrow-down
- icon-arrow-down-left
- icon-arrow-left
- icon-arrow-up-left2
- icon-arrow-up2
- icon-arrow-up-right2
- icon-arrow-right2
- icon-arrow-down-right2
- icon-arrow-down2
- icon-arrow-down-left2
- icon-arrow-left2
- icon-arrow-up-left3
- icon-arrow-up3
- icon-arrow-up-right3
- icon-arrow-right3
- icon-arrow-down-right3
- icon-arrow-down3
- icon-arrow-down-left3
- icon-arrow-left3
- icon-tab
- icon-checkbox-checked
- icon-checkbox-unchecked
- icon-checkbox-partial
- icon-radio-checked
- icon-radio-unchecked
- icon-crop
- icon-scissors
- icon-filter
- icon-filter2
- icon-font
- icon-text-height
- icon-text-width
- icon-bold
- icon-underline
- icon-italic
- icon-strikethrough
- icon-omega
- icon-sigma
- icon-table
- icon-table2
- icon-insert-template
- icon-pilcrow
- icon-lefttoright
- icon-righttoleft
- icon-paragraph-left
- icon-paragraph-center
- icon-paragraph-right
- icon-paragraph-justify
- icon-paragraph-left2
- icon-paragraph-center2
- icon-paragraph-right2
- icon-paragraph-justify2
- icon-indent-increase
- icon-indent-decrease
- icon-newtab
- icon-embed
- icon-code
- icon-console
- icon-share
- icon-mail
- icon-mail2
- icon-mail3
- icon-mail4
- icon-google
- icon-googleplus
- icon-googleplus2
- icon-googleplus3
- icon-googleplus4
- icon-google-drive
- icon-facebook
- icon-facebook2
- icon-facebook3
- icon-instagram
- icon-twitter
- icon-twitter2
- icon-twitter3
- icon-feed2
- icon-feed3
- icon-feed4
- icon-youtube
- icon-youtube2
- icon-vimeo
- icon-vimeo2
- icon-vimeo3
- icon-lanyrd
- icon-flickr
- icon-flickr2
- icon-flickr3
- icon-flickr4
- icon-picassa
- icon-picassa2
- icon-dribbble
- icon-dribbble2
- icon-dribbble3
- icon-forrst
- icon-forrst2
- icon-deviantart
- icon-deviantart2
- icon-steam
- icon-steam2
- icon-github
- icon-github2
- icon-github3
- icon-github4
- icon-github5
- icon-wordpress
- icon-wordpress2
- icon-joomla
- icon-blogger
- icon-blogger2
- icon-tumblr
- icon-tumblr2
- icon-yahoo
- icon-tux
- icon-apple
- icon-finder
- icon-android
- icon-windows
- icon-windows8
- icon-soundcloud
- icon-soundcloud2
- icon-skype
- icon-reddit
- icon-linkedin
- icon-lastfm
- icon-lastfm2
- icon-delicious
- icon-stumbleupon
- icon-stumbleupon2
- icon-stackoverflow
- icon-pinterest
- icon-pinterest2
- icon-xing
- icon-xing2
- icon-flattr
- icon-foursquare
- icon-foursquare2
- icon-paypal
- icon-paypal2
- icon-paypal3
- icon-yelp
- icon-libreoffice
- icon-file-pdf
- icon-file-openoffice
- icon-file-word
- icon-file-excel
- icon-file-zip
- icon-file-powerpoint
- icon-file-xml
- icon-file-css
- icon-html5
- icon-html52
- icon-css3
- icon-chrome
- icon-firefox
- icon-IE
- icon-opera
- icon-safari
- icon-IcoMoon
